MvcPL/Models/ResultViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace MvcPL.Models
{
    public class ResultViewModel
    {
        public int Id { get; set; }
        public int Place { get; set; }
        public double Points { get; set; }
        [Display(Name = "Name of the athlete")]
        public string AthleteName { get; set; }
        public string CompetitionTitle { get; set; }
        public string CompetitionProgram { get; set; }
    }
}

MvcPL/Controllers/ResultsController.cs
using BLL.Interface.Entities;
using BLL.Interface.Services;
using MvcPL.Infrastructure;
using MvcPL.Models;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcPL.Controllers
{
    [CustomExceptionFilter]
    [Authorize(Roles = "admin")]
    public class ResultsController : Controller
    {
        private readonly IResultService resultService;
        private readonly IAthleteService athleteService;
        private readonly ICompetitionService competitionService;
        public ResultsController(IResultService resultService, IAthleteService athleteService, ICompetitionService competitionService)
        {
            this.resultService = resultService;
            this.athleteService = athleteService;
            this.competitionService = competitionService;
        }

        public ActionResult ResultList()
        {
            ViewBag.NumOfPage = 0;
            return View(resultService.GetAllResultEntities(0)
                .Select(result => result.ToResultView()));
        }

        public ActionResult ResultsListPartial(int? pageNum)
        {
            if (pageNum == null || pageNum.Value < 0)
                return HttpNotFound();
            var model = resultService.GetAllResultEntities(pageNum.Value)
                .Select(result => result.ToResultView());
            if (model == null || model.Count() == 0) return HttpNotFound();
            ViewBag.NumOfPage = pageNum.Value;
            return PartialView("ResultsPartial", model);
        }

        [HttpGet]
        public ActionResult AddResults()
        {
            return View();
        }

        [HttpPost]
        public ActionResult AddResults(HttpPostedFileBase file)
        {
            String destinationPath = Server.MapPath("~/Uploads");
            String fileName = file.FileName;
            String path = Path.Combine(destinationPath, fileName);
            file.SaveAs(path);
            ResultsAddModel newResult = null;
            string fileFormat = ConfigurationManager.AppSettings["FileFormat"];
            using (StreamReader sr = new StreamReader(path, System.Text.Encoding.Default))
            {
                while (!sr.EndOfStream)
                {
                    string data = sr.ReadLine();
                    if (data != fileFormat)
                    {
                        newResult = ResultHelper.ParseAndWriteResultString(data);
                        if (newResult != null)
                            if (newResult.DateEnd >= newResult.DateBegin)
                                resultService.CreateResult(newResult.ToResultEntity(),
                                           newResult.ToAthleteEntity(), newResult.ToCompetitionEntity());
                    }
                }
            }

            return RedirectToAction("ResultList");
        }

        [HttpGet]
        public ActionResult EditResult(int? index)
        {
            if (index == null)
            {
                return HttpNotFound();
            }
            var result = resultService.GetResultById(index.Value);
            var competition = competitionService.GetCompetitionById(result.CompetitionId);
            var athlete = athleteService.GetAthleteById(result.AthleteId);
            ViewBag.ResultId = result.Id;
            ViewBag.AthleteId = athlete.Id;
            ViewBag.CompetitionId = competition.Id;
            ViewBag.Action = "Edit";
            return View("AddResult", new ResultsAddModel()
                {
                    AthleteName = athlete.AthleteName,
                    HorseName = athlete.HorseName,
                    Place = result.Place,
                    Points = result.Points,
                    CompetitionTitle = competition.Title,
                    CompetitionProgram = competition.Program,
                    DateBegin = competition.DateBegin,
                    DateEnd = competition.DateEnd,
                });
        }
        [HttpPost]
        public ActionResult EditResult(ResultsAddModel changedResult, int resultId,
            int athleteId, int competitionId)
        {
            resultService.EditResult(changedResult.ToResultEntity(resultId));
            athleteService.EditAthlete(changedResult.ToAthleteEntity(athleteId));
            competitionService.EditCompetition(changedResult.ToCompetitionEntity(competitionId));
            return RedirectToAction("ResultList");
        }

        [HttpGet]
        public ActionResult AddResult()
        {
            ViewBag.Action = "Add";
            return View();
        }

        [HttpPost]
        public ActionResult AddResult(ResultsAddModel newResult)
        {
            if (newResult.DateEnd >= newResult.DateBegin)
                resultService.CreateResult(newResult.ToResultEntity(), newResult.ToAthleteEntity(),
                    newResult.ToCompetitionEntity());
            return RedirectToAction("ResultList");
        }

        [HttpGet]
        public ActionResult DeleteResult(int index)
        {
            ViewBag.Index = index;
            return View("ConfirmAction");
        }

        [HttpPost]
        public ActionResult DeleteResult(int? index)
        {
            if (index == null)
            {
                return HttpNotFound();
            }
            resultService.DeleteResult(index.Value);
            return RedirectToAction("ResultList");
        }

        [HttpGet]
        public ActionResult DeleteAllResults(int? index)
        {
            return View("ConfirmAction");
        }

        [HttpPost]
        public ActionResult DeleteAllResults()
        {
            resultService.DeleteAllResults();
            return RedirectToAction("ResultList");
        }
    }
}

MvcPL/Views/Results/AddResult.cshtml
@model MvcPL.Models.ResultsAddModel

@{
    ViewBag.Title = "AddResult";
}

<legend>AddResult</legend>


@using (Html.BeginForm(new {
                                resultId = ViewBag.ResultId,
                                athleteId = ViewBag.AthleteId,
                                competitionId = ViewBag.CompetitionId
                            }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <div class="editor-label">
            @Html.LabelFor(model => model.AthleteName)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.AthleteName)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.HorseName)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.HorseName)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.Place)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Place)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.Points)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Points)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.CompetitionTitle)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.CompetitionTitle)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.CompetitionProgram)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.CompetitionProgram)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.DateBegin)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.DateBegin)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.DateEnd)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.DateEnd)
        </div>
        <br />
        <div>
            <button type="submit" class="btn btn-primary">@ViewBag.Action</button>
            @Html.ActionLink("Cancel", "ResultList", "Results", null, new { @class = "btn btn-default" })
        </div>
    </fieldset>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MvcPL/Views/Results/AddResults.cshtml
@{
    ViewBag.Title = "Add results";
}
<fieldset>
    <h3>Select a file to upload results</h3>
    @using (Html.BeginForm("AddResults", "Results", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        <div>
            <input type="file" name="file" />
        </div>
        <div>
            <input type="submit" value="Upload" />
        </div>
    }
</fieldset>

MvcPL/Views/Results/ConfirmAction.cshtml
@{
    ViewBag.Title = "ConfirmAction";
}

<h2>ConfirmAction</h2>

@using (Html.BeginForm(new {index = ViewBag.Index} ))
{
    @Html.AntiForgeryToken()
    <fieldset>
        <legend>Do action?</legend>

        <br />
        <div>
            <button type="submit" class="btn btn-primary">Yes</button>
            @Html.ActionLink("Cancel", "ResultList", "Results", null, new { @class = "btn btn-default" })
        </div>
    </fieldset>
}

MvcPL/Views/Results/ResultList.cshtml
@model IEnumerable<MvcPL.Models.ResultViewModel>

@{
    ViewBag.Title = "Result list";
    String adminName = System.Configuration.ConfigurationManager.AppSettings["AdminRoleName"];
}

<legend>Result list</legend>
@if (User.IsInRole(adminName))
{
    <p>
        @Html.ActionLink("Create new", "AddResult", null, new { @class = "btn btn-default" })
        @Html.ActionLink("Delete all", "DeleteAllResults", null, new { @class = "btn btn-default" })
    </p>
}
<table class="table table-striped table-hover ">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Place)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Points)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.AthleteName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CompetitionTitle)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CompetitionProgram)
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Place)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Points)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.AthleteName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CompetitionTitle)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CompetitionProgram)
                </td>
                @if (User.IsInRole(adminName))
                {
                    <td>
                        @Html.ActionLink("Edit", "EditResult", new { index = item.Id }) ||
                        @Html.ActionLink("Delete", "DeleteResult", new {  index = item.Id  })
                    </td>
                }
            </tr>
        }
    </tbody>
</table>

MvcPL/Views/Results/ResultsPartial.cshtml
@model IEnumerable<MvcPL.Models.ResultViewModel>

@{
    int numOfPage = ViewBag.NumOfPage + 1;
}

<legend>Result list, page @numOfPage</legend>

@Html.Partial("_Results")

@Ajax.ActionLink("Previous", "ResultsListPartial", "Results", new { pageNum = ViewBag.NumOfPage - 1 },
                                    new AjaxOptions { UpdateTargetId = "resultsList" }, new { @class = "btn btn-default" })
@Ajax.ActionLink("Next", "ResultsListPartial", "Results",
                                        new { pageNum = ViewBag.NumOfPage + 1 },
                                new AjaxOptions { UpdateTargetId = "resultsList" }, new { @class = "btn btn-default" })